### ISSUE TITLE
JAWS with Chrome links visually hidden text are read out without spaces 

### ISSUE THREAD

**Issue by nickcolley** [FreedomScientific/VFO-standards-support#372]
### Overview

Test case: https://output.jsbin.com/jorocat

1. Tab to link that reads 'Delete'

```html
  <a href="#">Link in page</a>
  <br>
  <button>
    Open all<span class="visually-hidden"> sections</span>
  </button>
  <br>
  <a href="#">
    Delete<span class="visually-hidden"> name</span>
  </a>
```

```css
.visually-hidden {
  position: absolute !important;
  width: 1px !important;
  height: 1px !important;
  margin: 0 !important;
  padding: 0 !important;
  overflow: hidden !important;
  clip: rect(0 0 0 0) !important;
  -webkit-clip-path: inset(50%) !important;
          clip-path: inset(50%) !important;
  border: 0 !important;
  white-space: nowrap !important;
}
```

JAWS: 2020
Chrome version: 79.0.3945.130

### Expected result

Announces "Delete name"

### Actual result

Announces "Deletename"
